version: '3.5'

services:
  users-web-api:
    build:
      context: .
      dockerfile: ./users-web/Dockerfile
    hostname: users-web-api
    depends_on:
      - oracle
    ports:
      - "8080:8080"
    networks:
      - crud
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521:xe
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_THREADS_VIRTUAL=false
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '2.0GB'
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    hostname: oracle
    environment:
      - ORACLE_PWD=123456
    volumes:
      - oracle_data:/opt/oracle/oradata
    ports:
      - "1521:1521"
    networks:
      - crud
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '2GB'
#  postgres:
#    image: postgres:latest
#    hostname: postgres
#    environment:
#      - POSTGRES_DB=app
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=123456
#    ports:
#      - "5432:5432"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: '1GB'

networks:
  crud:
    driver: bridge

volumes:
  oracle_data: {}