server:
  servlet:
    context-path: /v1

spring:
  r2dbc:
    url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/app}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: none